### ISSUE TITLE
source/action_cable_overview.md 5-2-stable

### ISSUE THREAD

**Issue by SunDi3yansyah** [rails-id/guides#6]
## Branch: action-cable-overview

- [source/action_cable_overview.md](https://github.com/rails-id/guides/blob/action-cable-overview/source/action_cable_overview.md)

## Daftar Isi

- [x] Action Cable Overview
    - [x] Introduction
    - [x] What is Pub/Sub
    - [x] Server-Side Components
        - [x] Connections
        - [x] Channels
    - [x] Client-Side Components
        - [x] Connections
    - [x] Client-Server Interactions
        - [x] Streams
        - [x] Broadcasting
        - [x] Subscriptions
        - [x] Passing Parameters to Channels
        - [x] Rebroadcasting a Message
    - [x] Full-Stack Examples
        - [x] Example 1: User Appearances
        - [x] Example 2: Receiving New Web Notifications
        - [x] More Complete Examples
    - [x] Configuration
        - [x] Subscription Adapter
        - [x] Allowed Request Origins
        - [x] Consumer Configuration
        - [x] Other Configurations
    - [x] Running Standalone Cable Servers
        - [x] In App
        - [x] Standalone
        - [x] Notes
    - [x] Dependencies
    - [x] Deployment

**Comment by wicky-info** [comment]
ada yang tahu terjemahan 'cookie' ke bahasa Indonesia  ? atau tidak perlu di terjemahkan

**Comment by SunDi3yansyah** [comment]
cookie saja :+1: itu jangan di terjemahkan karena kalau di terjemahkan jadi roti

**Comment by SunDi3yansyah** [comment]
> ada yang tahu terjemahan 'cookie' ke bahasa Indonesia ? atau tidak perlu di terjemahkan

cookie saja :+1: itu jangan di terjemahkan karena kalau di terjemahkan jadi roti

**Comment by wicky-info** [comment]
wkwkkww selama  ini yang di tunggu" itu rotiiiii..tambah kopi lagii mantapss wkwkkww

**Comment by wicky-info** [comment]
Siaap mastah hahhaha

**Comment by wicky-info** [comment]
Apakah 'params' sama dengan 'parameter' ? kalau params terjemahannya tetap sama params

**Comment by SunDi3yansyah** [comment]
Yup benar mas, params => parameter

**Comment by wicky-info** [comment]
full-stack tidak perlu di terjemahkan ? jadinya 'tumpukan penuh'

**Comment by SunDi3yansyah** [comment]
> full-stack tidak perlu di terjemahkan ? jadinya 'tumpukan penuh'

tidak perlu diterjemahkan
